import Head from "next/head";
import About from "../components/about/About";
import HeroSection from "../components/HerSection/HeroSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Haya Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroSection />
      <About/>
    </div>
  );
}
